fixing options

diff --git a/gitrepo/usr/bin/gitrepo b/gitrepo/usr/bin/gitrepo
--- a/gitrepo/usr/bin/gitrepo
+++ b/gitrepo/usr/bin/gitrepo
@@ -1,6 +1,47 @@
-#!/bin/sh
-read -p 'Github username :' username;
-read -p 'Repository Name :' repo_name 
-test -z $repo_name && echo "Repo name must be filled" 1>&2 
-test -z $username && echo "Username must be filled" 1>&2
-curl -u $username https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
+#!/bin/bash
+
+function _help()
+{
+	echo "
+Gitrepo 0.01 ( https://github.com/dekiakbar/LinuxShell )
+Usage: gitrepo [Options] 
+[Options]
+	-c : Check and list all repository
+	-h : Show this help
+	-n : Create new repository
+Happy code"
+}
+
+_help
+
+while getopts ":c:n:h" opt; do
+	case $opt in
+	  	c)  read -p "Github Username :" username
+			if [[ -n $username ]]; then
+				curl -g -u $username  https://api.github.com/user/repos
+			else
+				echo "Username must be filled"
+			fi
+			;;
+
+	    h)  _help
+			;;
+
+	    n)  read -p 'Github username :' username
+			read -p 'Repository Name :' reponame 
+			if [[ -n $username && -n $reponame ]]; then
+				curl -u $username https://api.github.com/user/repos -d "{\"name\":\"$repo_name\"}"
+			else if [[ -z $username ]]; then
+				echo "Username must be filled"
+			else if [[ -z $reponame ]]; then
+				echo "Repository name must be filled"
+			fi
+			fi
+			fi
+	      ;;
+	    \?)
+	      echo "Invalid option: -$OPTARG" >&2
+	      ;;
+	esac
+done
+
